import type { ReportData } from "./csvExport";
import { isInRange } from "./dateRanges";
import type { FinanceDashboardState } from "@/components/dashboard/useFinanceDashboard";
import { getDaysLeft } from "@/lib/dreamsGoals";

type AutoTableUserOptions = {
  head?: unknown[][];
  body?: unknown[][];
  startY?: number;
  theme?: string;
  headStyles?: Record<string, unknown>;
  bodyStyles?: Record<string, unknown>;
  alternateRowStyles?: Record<string, unknown>;
  styles?: Record<string, unknown>;
  margin?: { left?: number; right?: number; top?: number; bottom?: number };
  tableLineColor?: number[];
  tableLineWidth?: number;
};

declare module "jspdf" {
  interface jsPDF {
    autoTable: (options: AutoTableUserOptions) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

const HEADER_BG: [number, number, number] = [13, 17, 23];
const STRIPE_BG: [number, number, number] = [17, 20, 25];
const ACCENT: [number, number, number] = [52, 211, 153];
const TEXT_LIGHT: [number, number, number] = [245, 245, 245];
const TEXT_MUTED: [number, number, number] = [150, 150, 160];
const CELL_BG: [number, number, number] = [22, 26, 33];

function headStyles() {
  return {
    fillColor: HEADER_BG,
    textColor: TEXT_LIGHT,
    fontStyle: "bold",
    fontSize: 8,
  };
}

function bodyStyles() {
  return {
    fillColor: CELL_BG,
    textColor: TEXT_LIGHT,
    fontSize: 8,
  };
}

function altRowStyles() {
  return { fillColor: STRIPE_BG };
}

function fmt(n: number, sym: string) {
  return `${sym}${n.toFixed(2)}`;
}

function findPersonName(id: unknown, people: { id: string | number; name: string }[]): string {
  return people.find((p) => String(p.id) === String(id))?.name ?? "";
}

export async function generatePDF(data: ReportData, state: FinanceDashboardState): Promise<void> {
  // Dynamic imports to avoid SSR issues
  const { jsPDF } = await import("jspdf");
  await import("jspdf-autotable");

  const {
    range,
    incomes,
    expenses,
    transfers,
    lendingTransactions,
    people,
    liabilities,
    savingsBuckets,
    assets,
    locationTags,
    goals,
    bankBalance,
    cashBalance,
    usableBalance,
    netWorth,
    activeLent,
    activeBorrowed,
    currencySymbol: sym,
    userNameMe,
    userNameSpouse,
  } = data;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();
  const ML = 14;
  const MR = 14;
  const tableWidth = PAGE_W - ML - MR;

  function sectionTitle(title: string, y: number): number {
    doc.setFontSize(11);
    doc.setTextColor(...ACCENT);
    doc.text(title, ML, y);
    doc.setDrawColor(...ACCENT);
    doc.setLineWidth(0.4);
    doc.line(ML, y + 1.5, ML + tableWidth, y + 1.5);
    return y + 7;
  }

  function ensureSpace(needed: number): number {
    const lastY = doc.lastAutoTable?.finalY ?? 20;
    if (lastY + needed > PAGE_H - 20) {
      doc.addPage();
      return 20;
    }
    return lastY + 8;
  }

  // ── PAGE 1: COVER ──────────────────────────────────────────────────────────
  doc.setFillColor(...HEADER_BG);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");

  // App name
  doc.setFontSize(11);
  doc.setTextColor(...TEXT_MUTED);
  doc.text("Money Control", ML, 30);

  // Big title
  doc.setFontSize(34);
  doc.setTextColor(...TEXT_LIGHT);
  doc.text("Financial Report", ML, 55);

  // Accent line
  doc.setDrawColor(...ACCENT);
  doc.setLineWidth(1.2);
  doc.line(ML, 62, ML + 80, 62);

  // Report details
  doc.setFontSize(12);
  doc.setTextColor(...ACCENT);
  doc.text(range.label, ML, 80);

  doc.setFontSize(10);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(`Generated: ${new Date().toLocaleString("en-AU")}`, ML, 92);
  doc.text(`Currency: ${sym} (AUD)`, ML, 100);
  doc.text(`Users: ${userNameMe} / ${userNameSpouse}`, ML, 108);

  // Footer on cover
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_MUTED);
  doc.text("Generated by Money Control • Personal Finance App", ML, PAGE_H - 15);

  // ── PAGE 2: FINANCIAL SUMMARY ─────────────────────────────────────────────
  doc.addPage();
  doc.setFillColor(...HEADER_BG);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");

  let y = 20;
  y = sectionTitle("Financial Summary", y);

  doc.autoTable({
    head: [["Metric", "Value"]],
    body: [
      ["Bank Balance", fmt(bankBalance, sym)],
      ["Cash Balance", fmt(cashBalance, sym)],
      ["Usable Balance", fmt(usableBalance, sym)],
      ["Net Worth", fmt(netWorth, sym)],
      ["Active Lent", fmt(activeLent, sym)],
      ["Active Borrowed", fmt(activeBorrowed, sym)],
      ["Monthly Income", fmt(state.monthlyIncome, sym)],
      ["Monthly Expenses", fmt(state.monthlyExpenses, sym)],
    ],
    startY: y,
    theme: "plain",
    headStyles: headStyles(),
    bodyStyles: bodyStyles(),
    alternateRowStyles: altRowStyles(),
    margin: { left: ML, right: MR },
  });

  // Monthly analytics table
  const monthly = state.financialAnalytics.monthly;
  if (monthly.length > 0) {
    y = ensureSpace(30);
    y = sectionTitle("Monthly Income vs Expenses", y);
    doc.autoTable({
      head: [["Month", "Income", "Expenses", "Net"]],
      body: monthly.map((m) => [
        m.month,
        fmt(m.income, sym),
        fmt(m.expenses, sym),
        fmt(m.income - m.expenses, sym),
      ]),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // Category breakdown
  const categories = state.financialAnalytics.categories;
  if (categories.length > 0) {
    y = ensureSpace(30);
    y = sectionTitle("Category Spending", y);
    doc.autoTable({
      head: [["Category", "Amount"]],
      body: categories.map((c) => [c.name, fmt(c.value, sym)]),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // ── INCOME PAGE ────────────────────────────────────────────────────────────
  const filteredIncomes = incomes.filter((i) => isInRange(i.date, range));
  if (filteredIncomes.length > 0) {
    doc.addPage();
    doc.setFillColor(...HEADER_BG);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    y = sectionTitle(`Income (${range.label})`, 20);
    doc.autoTable({
      head: [["Date", "Type", "Source", "Amount", "Bank", "Cash", "Added By"]],
      body: filteredIncomes.map((i) => [
        i.date,
        i.income_type,
        i.source,
        fmt(i.amount, sym),
        fmt(i.amount - (i.cash_received ?? 0), sym),
        fmt(i.cash_received ?? 0, sym),
        i.addedBy === "spouse" ? userNameSpouse : userNameMe,
      ]),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // ── EXPENSES PAGE ──────────────────────────────────────────────────────────
  const filteredExpenses = expenses.filter((e) => isInRange(e.date, range));
  if (filteredExpenses.length > 0) {
    doc.addPage();
    doc.setFillColor(...HEADER_BG);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    y = sectionTitle(`Expenses (${range.label})`, 20);
    doc.autoTable({
      head: [["Date", "Category", "Amount", "Account", "Method", "Recurring", "Notes"]],
      body: filteredExpenses.map((e) => [
        e.date,
        e.category,
        fmt(e.amount, sym),
        e.account,
        e.paymentMethod ?? "",
        e.isRecurring ? `Yes (${e.recurringFrequency ?? ""})` : "No",
        e.notes?.slice(0, 50) ?? "",
      ]),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
      styles: { fontSize: 7.5, overflow: "linebreak", cellWidth: "wrap" },
    });
  }

  // ── TRANSFERS ──────────────────────────────────────────────────────────────
  const filteredTransfers = transfers.filter((t) => isInRange(t.date, range));
  if (filteredTransfers.length > 0) {
    doc.addPage();
    doc.setFillColor(...HEADER_BG);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    y = sectionTitle(`Transfers (${range.label})`, 20);
    doc.autoTable({
      head: [["Date", "From", "To", "Amount", "Notes"]],
      body: filteredTransfers.map((t) => [
        t.date,
        t.from_bucket,
        t.to_bucket,
        fmt(t.amount, sym),
        t.notes?.slice(0, 60) ?? "",
      ]),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // ── LENDING ────────────────────────────────────────────────────────────────
  const filteredLending = lendingTransactions.filter((l) => isInRange(l.date, range));
  if (filteredLending.length > 0) {
    doc.addPage();
    doc.setFillColor(...HEADER_BG);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    y = sectionTitle(`Lending / Borrowing (${range.label})`, 20);
    doc.autoTable({
      head: [["Date", "Person", "Type", "Amount", "Account", "Affects Balance", "Notes"]],
      body: filteredLending.map((l) => [
        l.date,
        findPersonName(l.personId, people),
        l.type,
        fmt(l.amount, sym),
        l.account ?? "",
        l.affectsAccountBalance ? "Yes" : "No",
        (l.note ?? "").slice(0, 50),
      ]),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // ── LIABILITIES ────────────────────────────────────────────────────────────
  if (liabilities.length > 0) {
    doc.addPage();
    doc.setFillColor(...HEADER_BG);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    y = sectionTitle("Liabilities (Full Snapshot)", 20);
    doc.autoTable({
      head: [["Name", "Type", "Provider", "Original", "Outstanding", "Status"]],
      body: liabilities.map((l) => [
        l.name,
        l.type,
        l.provider,
        fmt(l.originalAmount, sym),
        fmt(l.outstandingBalance, sym),
        l.status,
      ]),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // ── SAVINGS BUCKETS ────────────────────────────────────────────────────────
  if (savingsBuckets.length > 0) {
    doc.addPage();
    doc.setFillColor(...HEADER_BG);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    y = sectionTitle("Savings Buckets (Full Snapshot)", 20);
    doc.autoTable({
      head: [["Name", "Storage Label", "Balance", "Target", "Progress"]],
      body: savingsBuckets.map((b) => {
        const pct = b.targetAmount > 0
          ? ((b.currentBalance / b.targetAmount) * 100).toFixed(1) + "%"
          : "N/A";
        return [b.name, b.linkedStorageLabel, fmt(b.currentBalance, sym), fmt(b.targetAmount, sym), pct];
      }),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // ── ASSET VAULT ────────────────────────────────────────────────────────────
  if (assets.length > 0) {
    doc.addPage();
    doc.setFillColor(...HEADER_BG);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    y = sectionTitle("Asset Vault (Full Snapshot)", 20);
    doc.autoTable({
      head: [["Title", "Type", "Location Tags", "Date"]],
      body: assets.map((a) => {
        const tagNames = a.locationTagIds
          .map((tid) => locationTags.find((t) => t.id === tid)?.name ?? "")
          .filter(Boolean)
          .join(", ");
        return [a.title, a.assetType, tagNames, a.date];
      }),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // ── DREAMS & GOALS ─────────────────────────────────────────────────────────
  if (goals.length > 0) {
    doc.addPage();
    doc.setFillColor(...HEADER_BG);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    y = sectionTitle("Dreams & Goals (Full Snapshot)", 20);
    doc.autoTable({
      head: [["Title", "Category", "Target Date", "Days Left", "Status"]],
      body: goals.map((g) => {
        const daysLeft = g.targetDate ? getDaysLeft(g.targetDate) : null;
        return [
          g.title,
          g.category,
          g.targetDate ?? "",
          daysLeft != null ? String(daysLeft) : "",
          g.status,
        ];
      }),
      startY: y,
      theme: "plain",
      headStyles: headStyles(),
      bodyStyles: bodyStyles(),
      alternateRowStyles: altRowStyles(),
      margin: { left: ML, right: MR },
    });
  }

  // Add page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_W - MR, PAGE_H - 8, { align: "right" });
    doc.text("Money Control", ML, PAGE_H - 8);
  }

  const filename = `finance-report-${data.range.filenameSlug}.pdf`;
  doc.save(filename);
}
